# t04 — make_cold_variant (S0.3 §2): determinism, collateral accounting, ID-universe
# byte-identity, warm/cold partition correctness, zero-train-user drop rule — on a toy
# canonical dir, then sanity on the real V1 variant if generated.
import filecmp
import os
import shutil
import sys
import tempfile

import pandas as pd

from _harness import make_check, build_toy_canonical, REPO_ROOT

sys.path.insert(0, os.path.join(REPO_ROOT, 'data', 'hm'))
from make_cold_variant import make_cold_variant, sample_cold_items

check, fails = make_check()

tmp = tempfile.mkdtemp(prefix='s0_t04_')
canon = os.path.join(tmp, 'toy')
build_toy_canonical(canon)

out1, out2 = os.path.join(tmp, 'toy_cold'), os.path.join(tmp, 'toy_cold2')
r1 = make_cold_variant(canon, out1)
r2 = make_cold_variant(canon, out2)

# --- determinism ---
same = all(filecmp.cmp(os.path.join(out1, f), os.path.join(out2, f), shallow=False)
           for f in ('cold_items.csv', 'cold_test.csv', 'listening_history_train.csv',
                     'listening_history_val.csv', 'listening_history_test.csv'))
check("regeneration is byte-identical (same seed)", same)

# --- ID universe byte-identical to canonical ---
check("user_ids/item_ids/item_features copied byte-identically",
      all(filecmp.cmp(os.path.join(canon, f), os.path.join(out1, f), shallow=False)
          for f in ('user_ids.csv', 'item_ids.csv', 'item_features.csv')))

cold_items = pd.read_csv(os.path.join(out1, 'cold_items.csv'))
cold_test = pd.read_csv(os.path.join(out1, 'cold_test.csv'))
C = set(cold_items['item_id'])
tr = pd.read_csv(os.path.join(out1, 'listening_history_train.csv'))
va = pd.read_csv(os.path.join(out1, 'listening_history_val.csv'))
te = pd.read_csv(os.path.join(out1, 'listening_history_test.csv'))
ctr = pd.read_csv(os.path.join(canon, 'listening_history_train.csv'))

# --- cold set properties ---
check("cold size ≈ 20% of eligible", abs(len(C) - 0.2 * r1['n_items_eligible']) <= 5,
      f"{len(C)} of {r1['n_items_eligible']}")
check("every cold item has >=1 canonical-train interaction",
      C.issubset(set(ctr['item_id'])))
check("cold_items covers all 10 deciles", sorted(cold_items['pop_decile'].unique()) == list(range(10)))

# --- partition correctness ---
check("variant train/val/test contain NO cold item",
      not any(df['item_id'].isin(C).any() for df in (tr, va, te)))
check("every cold_test row is a cold item", cold_test['item_id'].isin(C).all())
check("orig_split tags well-formed", set(cold_test['orig_split']) <= {'train', 'val', 'test'})

# --- conservation: canonical rows == variant rows + cold rows + dropped rows ---
n_canon = sum(r1['canonical_rows'].values())
n_var = sum(r1['variant_rows'].values())
check("row conservation", n_canon == n_var + r1['cold_test_rows'] + r1['dropped_zero_train_rows'],
      f"{n_canon} == {n_var} + {r1['cold_test_rows']} + {r1['dropped_zero_train_rows']}")

# --- zero-train-user drop rule ---
users_with_train = set(tr['user_id'])
check("no cold_test row belongs to a user without variant-train rows",
      cold_test['user_id'].isin(users_with_train).all())

# --- sample_cold_items pure-function determinism ---
c_a, _ = sample_cold_items(ctr)
c_b, _ = sample_cold_items(ctr)
check("sample_cold_items deterministic", c_a['item_id'].tolist() == c_b['item_id'].tolist())

# --- real V1 variant (generated by the committed generator) ---
v1_cold = os.path.join(REPO_ROOT, 'data', 'hm_1_month_cold')
v1 = os.path.join(REPO_ROOT, 'data', 'hm_1_month')
if os.path.exists(os.path.join(v1_cold, 'cold_variant_report.json')):
    import json
    with open(os.path.join(v1_cold, 'cold_variant_report.json')) as f:
        rep = json.load(f)
    check("V1: 2,730 cold items (20% of 13,648 eligible)",
          rep['n_cold_items'] == 2730 and rep['n_items_eligible'] == 13648,
          f"{rep['n_cold_items']} / {rep['n_items_eligible']}")
    check("V1: row conservation",
          sum(rep['canonical_rows'].values()) ==
          sum(rep['variant_rows'].values()) + rep['cold_test_rows'] + rep['dropped_zero_train_rows'])
    check("V1: ID files byte-identical",
          all(filecmp.cmp(os.path.join(v1, f), os.path.join(v1_cold, f), shallow=False)
              for f in ('user_ids.csv', 'item_ids.csv', 'item_features.csv')))
    v1_tr = pd.read_csv(os.path.join(v1_cold, 'listening_history_train.csv'), usecols=['item_id'])
    v1_ci = set(pd.read_csv(os.path.join(v1_cold, 'cold_items.csv'))['item_id'])
    check("V1: no cold item in variant train", not v1_tr['item_id'].isin(v1_ci).any())
    # determinism against the committed artifact
    c_v1, _ = sample_cold_items(pd.read_csv(os.path.join(v1, 'listening_history_train.csv')))
    check("V1: committed cold set reproducible from canonical train",
          c_v1['item_id'].tolist() == sorted(v1_ci))
else:
    print("[SKIP] data/hm_1_month_cold not generated")

shutil.rmtree(tmp, ignore_errors=True)

print(f"\n{'ALL PASS' if not fails else f'{len(fails)} FAILURES: {fails}'}")
sys.exit(0 if not fails else 1)
