#!/usr/bin/env python3
"""B5 (LightFM / Kula 2015) reading-guide highlight pass.
Green = core/read-this, Yellow = secondary/if-time. Whole-passage word-box ranges
between a start and end phrase. Writes to a COPY; original untouched."""
import fitz, shutil, sys, os, re

SRC = "Master/literature/papers/B_feature_aware_mf/B5_kula_2015_lightfm_metadata_embeddings.pdf"
DST = "Master/literature/papers/B_feature_aware_mf/B5_kula_2015_lightfm_metadata_embeddings-annotated.pdf"

GREEN = (0.72, 0.90, 0.70)
YELLOW = (1.00, 0.93, 0.58)
OPACITY = 0.40

LIG = {"ﬁ": "fi", "ﬂ": "fl", "ﬀ": "ff", "ﬃ": "ffi", "ﬄ": "ffl"}
def norm(s):
    for k, v in LIG.items():
        s = s.replace(k, v)
    return re.sub(r"[^a-z0-9]", "", s.lower())

# (page_index, color, start_phrase, end_phrase, label)
PASSAGES = [
    # ---- page 1 ----
    (0, GREEN,  "In LightFM, like in a", "these features latent representations", "§1 sum-of-features idea"),
    (0, YELLOW, "Three factors conspire", "unsuitable for us", "§1 Lyst fashion challenge"),
    # ---- page 2 ----
    (1, YELLOW, "Such representations allow transfer learning", "suggests it should be", "§2.1 transfer-learning req"),
    (1, GREEN,  "second requirement by representing", "female users", "§2.1 linear-combination of features"),
    (1, GREEN,  "The latent representation of user", "latent vectors", "§2.2 user = sum of feature vectors"),
    (1, GREEN,  "prediction for user", "feature biases", "§2.2 dot-product prediction"),
    (1, GREEN,  "If the feature sets consist", "structure of user interactions", "§2.3 reduces to MF / extends MF"),
    # ---- page 3 ----
    (2, GREEN,  "The fact that LightFM contains", "specialised model in each scenario", "§2.3 CB↔MF spectrum"),
    (2, YELLOW, "From a theory standpoint", "resulting feature embeddings", "§3 special case of FMs"),
    # ---- page 4 ----
    (3, GREEN,  "In the warm-start, low-sparsity", "accurately than other hybrid models", "§6.1 metadata helps + collab crucial"),
    # ---- page 5 ----
    (4, GREEN,  "LightFM variants provide the best", "into the recommendation model", "§6.1 tags+about best (user metadata)"),
    (4, GREEN,  "Feature embeddings generated by the", "the semantic relationships", "§6.3 semantic feature embeddings"),
    (4, YELLOW, "LightFM performs very well even", "as 16 dimensions", "§6.2 strong at small d"),
    # ---- page 6 ----
    (5, GREEN,  "Rich information encoded in feature", "their latent factors", "§6.3 recommendation justification"),
    (6, YELLOW, "Secondly, there is no easy", "recommendation loss directly", "§8 visual/CNN future work"),
]

def find_range(words, phrase):
    toks = [norm(w) for w in phrase.split() if norm(w)]
    n = len(toks)
    nwords = [norm(w[4]) for w in words]
    for i in range(len(nwords) - n + 1):
        if nwords[i:i+n] == toks:
            return i, i + n - 1
    # fallback: tolerate words that got merged/split by joining
    joined = ""
    idx = []
    for i, w in enumerate(nwords):
        for _ in w:
            idx.append(i)
        joined += w
    target = "".join(toks)
    p = joined.find(target)
    if p >= 0:
        return idx[p], idx[p + len(target) - 1]
    return None

doc = fitz.open(SRC)
report = []
for pno, color, start, end, label in PASSAGES:
    page = doc[pno]
    words = page.get_text("words")
    words.sort(key=lambda w: (w[5], w[6], w[7]))  # block, line, word
    rs = find_range(words, start)
    re_ = find_range(words, end)
    if rs is None or re_ is None:
        report.append(f"  !! MISS p{pno+1} [{label}] start={'OK' if rs else 'MISS'} end={'OK' if re_ else 'MISS'}")
        continue
    i0, j1 = rs[0], re_[1]
    if j1 < i0:
        report.append(f"  !! ORDER p{pno+1} [{label}] end before start")
        continue
    seg = words[i0:j1+1]
    lines = {}
    for w in seg:
        key = (w[5], w[6])
        x0, y0, x1, y1 = w[0], w[1], w[2], w[3]
        if key not in lines:
            lines[key] = [x0, y0, x1, y1]
        else:
            b = lines[key]
            b[0] = min(b[0], x0); b[1] = min(b[1], y0)
            b[2] = max(b[2], x1); b[3] = max(b[3], y1)
    for b in lines.values():
        rect = fitz.Rect(b)
        a = page.add_highlight_annot(rect)
        a.set_colors(stroke=color)
        a.set_opacity(OPACITY)
        a.update()
    tag = "GREEN" if color == GREEN else "yellow"
    report.append(f"  ok  p{pno+1} {tag:6} [{label}] ({len(lines)} lines)")

doc.save(DST, garbage=4, deflate=True)
doc.close()
print(f"Saved: {DST}\n")
print("\n".join(report))
